### ISSUE TITLE
TypeError: Cannot read property 'number' of undefined

### ISSUE THREAD

**Issue by JcCadet62** [dieuhd/sonar-quality-gate#41]
Hello, 
I have this problem :

`Warning: Unexpected input(s) 'url', 'projectKey', valid inputs are ['entryPoint', 'args', 'login', 'skipScanner']
Run dieuhd/sonar-quality-gate@v1

         
/app/build/cli/core.js:147
        return ev.pull_request.number;
                               ^

TypeError: Cannot read property 'number' of undefined
    at Cli.getGithubPullNumber (/app/build/cli/core.js:147:32)
    at Cli.getMergeID (/app/build/cli/core.js:129:25)
    at new Cli (/app/build/cli/core.js:[24](https://github.com/NticoGroup/ntico-test-unit-test-sonar/actions/runs/4755115007/jobs/8448823884#step:16:25):[32](https://github.com/NticoGroup/ntico-test-unit-test-sonar/actions/runs/4755115007/jobs/8448823884#step:16:33))
    at Object.<anonymous> (/app/build/index.js:5:11)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)
    at internal/main/run_main_module.js:17:47`

How to solve it?

**Comment by JcCadet62** [comment]
For evenyone, the forget :
on: [pull_request]
