### ISSUE TITLE
TypeError: this.gitToken.replace is not a function

### ISSUE THREAD

**Issue by ZILosoft** [dieuhd/sonar-quality-gate#57]
when i run cli 
```
quality-gate -Dsonar.projectKey=project -Dsonar.host.url=https://sonarqube.local/ -Dsonar.pullrequest.key=23702 -Dsonar.pullrequest.branch=auto_update_configs -Dsonar.pullrequest.base=master -Dsonar.sourcesEncoding=UTF-8 --sonar.url=https://sonarqube.local/ --sonar.token=token --sonar.projectKey=project --git.merge_id=23702 --git.url=https://gitlab.local --git.token="111111111111111" --git.project_id=1
```
i got error 

```
                          _   _   _                                     _
   __ _   _   _    __ _  | | (_) | |_   _   _            __ _    __ _  | |_    ___
  / _` | | | | |  / _` | | | | | | __| | | | |  _____   / _` |  / _` | | __|  / _ \
 | (_| | | |_| | | (_| | | | | | | |_  | |_| | |_____| | (_| | | (_| | | |_  |  __/
  \__, |  \__,_|  \__,_| |_| |_|  \__|  \__, |          \__, |  \__,_|  \__|  \___|
     |_|                                |___/           |___/
--- START SCAN ---
/usr/local/lib/node_modules/sonar-quality-gate/build/cli/core.js:58
        this.gitToken = this.gitToken.replace(/['"]+/g, '');
                                      ^

TypeError: this.gitToken.replace is not a function
    at Cli.formatParameters (/usr/local/lib/node_modules/sonar-quality-gate/build/cli/core.js:58:39)
    at new Cli (/usr/local/lib/node_modules/sonar-quality-gate/build/cli/core.js:36:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/sonar-quality-gate/build/index.js:5:11)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

```

```
quality-gate -v
                          _   _   _                                     _
   __ _   _   _    __ _  | | (_) | |_   _   _            __ _    __ _  | |_    ___
  / _` | | | | |  / _` | | | | | | __| | | | |  _____   / _` |  / _` | | __|  / _ \
 | (_| | | |_| | | (_| | | | | | | |_  | |_| | |_____| | (_| | | (_| | | |_  |  __/
  \__, |  \__,_|  \__,_| |_| |_|  \__|  \__, |          \__, |  \__,_|  \__|  \___|
     |_|                                |___/           |___/
1.3.0
```

**Comment by dieuhd** [comment]
I fixed at #58
